# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "aws-sdk-s3" # AWS SDK for S3
gem 'pry' # debugging
gem 'nokogiri' # parsing