#!/usr/bin/env bash

echo "== delete objects =="
set -e

# Check for bucket name
if [ -z "$1" ]; then
  echo "Issue with bucket name"
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects \
--bucket "$BUCKET_NAME" \
--query "Contents[].{Key: Key}" \
--output json \
| jq '{Objects: ., Quiet: false}' > /tmp/objects.json

# https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-objects.html#examples
aws s3api delete-objects \
--bucket "$BUCKET_NAME" \
--delete file:///tmp/objects.json
# --delete "$(cat /tmp/objects.json)"