#!/usr/bin/env bash

echo "== deploy s3 bucket via CF"


STACK_NAME="s3-bucket-stack"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--stack-name "$STACK_NAME" \
--region ca-central-1